### ISSUE TITLE
Faulty implementation of LSTM

### ISSUE THREAD

**Issue by berkcoker** [carlthome/tensorflow-convlstm-cell#11]
Your implementation is incorrect. I suggest going over the paper again. You're confusing the hidden and output states.

**Comment by carlthome** [comment]
Thanks for your feedback @berkcoker!

Could you expand a little on what you mean is incorrect? What lines of code in particular are you referring to? Which paper are you referring to?

These are the ConvLSTM equations from [my reference](https://arxiv.org/pdf/1506.04214.pdf):
![image](https://cloud.githubusercontent.com/assets/1595907/26577089/79320e74-452b-11e7-85c7-bfb1d0e31af5.png)

And [this](https://github.com/tensorflow/tensorflow/blob/a23f782026a17697ddd860cf3ddea434dd9412f3/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L1326-L1350) is what I based the code of.

It looks right to me. 😕 

I guess I could add in a peephole if that's what you mean, but it hurts performance unless the output gate also uses the previous memory. It's not clear to me how important these details are in practice. Do you have any input?

**Comment by carlthome** [comment]
@berkcoker, could you clarify what particular details are faulty in the implementation? 

Note that in literature the hidden state is the output (the naming comes from vanilla RNNs that lack the cell state), e.g. one input projection and one hidden to hidden projection is done in LSTMs, but not an additional output projection (as that could be done after the recurrent connection instead with reshaping and a dense layer, which is a lot more computationally efficient).

I believe you've confused the peephole connections in Gers' LSTM equations with the hidden-to-hidden transition. Am I right?

**Comment by carlthome** [comment]
@berkcoker, care to clarify?

**Comment by carlthome** [comment]
@berkcoker, I'm closing this issue and marking it as invalid as it seems you've misread the LSTM equations (see my earlier replies). Feel free to reopen this issue with a clearer explanation of what is wrong in the implementation if you get around to it.
