### ISSUE TITLE
Usage of ConvGRU

### ISSUE THREAD

**Issue by leesunfreshing** [carlthome/tensorflow-convlstm-cell#12]
Hi, can you provide the completed example of using ConvGRU? When I invoke the cell, the Type error of super__init__ comes out. It seem super class should not take params according to the error...

**Comment by leesunfreshing** [comment]
By the way, the error is:
TypeError: object.__init__() takes no parameters

**Comment by carlthome** [comment]
You need to use the latest version of TensorFlow (1.2) as the RNN API was changed quite a bit, or use the [previous cell.py](https://github.com/carlthome/tensorflow-convlstm-cell/blob/1bab5a95231757ed270962cffd51a3c8dbe5b8af/cell.py).

**Comment by leesunfreshing** [comment]
Hi, just a simple reuse questions by using previous cell. In case I would like to reuse the params between two ConvGRU cells,  a simple reuse = True would do ,right?
For instance:
with tf.variable_scope('convgru1'):
       convgru1 = ConvGRUCell(..)
with tf.variable_scope('convgru1', reuse = True)
       convgru2 = ConvGRUCell(..)
would guarantee convgru1 and convgru2 share the same params, right?

**Comment by carlthome** [comment]
Yes, I believe so.
