### ISSUE TITLE
Make placeholder time major for RNN.

### ISSUE THREAD

**Issue by speedinghzl** [carlthome/tensorflow-convlstm-cell#14]
Hi @carlthome , thanks for your implementation!
I noticed that you remove the transposition for inputs in [README.md](https://github.com/carlthome/tensorflow-convlstm-cell/commit/43910e23e360c7f5fa2c571d87824cad63f6cc14).  
This makes me confused. Does the convlstm require inputs with time major?

**Comment by carlthome** [comment]
TensorFlow 1.2 fixed the transposition inside the RNN API to work with arbitrarily high dimensions, so it's no longer needed.
