### ISSUE TITLE
super() problem

### ISSUE THREAD

**Issue by gxdai** [carlthome/tensorflow-convlstm-cell#17]
Hi carlthome, 

I got the following problem when I tried to use the convLSTM cell. 
  File "demo.py", line 17, in <module>
    cell = ConvLSTMCell(shape, filters, kernel)
  File "/media/MMVCNYLOCAL/MMVC_NY/Guoxian_Dai/sourcecode/convLSTM/cell.py", line 11, in __init__
    super(ConvLSTMCell, self).__init__(_reuse=reuse)
TypeError: object.__init__() takes no parameters

**Comment by carlthome** [comment]
Update to TensorFlow 1.2.
