### ISSUE TITLE
get the prediction result?

### ISSUE THREAD

**Issue by miaoqinghua** [carlthome/tensorflow-convlstm-cell#26]
If the input is with size of [batches,time_steps,shape,channels], after running the  following codes, the shape of the outputs is [batches,time_step,X_size,Y_size,filters], how should I get the prediction of last time steps?
" cell = ConvLSTMCell(shape, filters, kernel)    
  outputs, state = tf.nn.dynamic_rnn(cell, inputs, dtype=inputs.dtype)"
I found in the RNN case, they would add two varivales Weight and bias, and using the following codes to get the final prediction, but I have problems defining the Weight and bias here.
 "  outputs = tf.unstack(tf.transpose(outputs, [1,0,2]))
    results = tf.matmul(outputs[-1], weights['out']) + biases['out']    # shape = (128, 10)

**Comment by carlthome** [comment]
If your output tensor `x` has the shape `[batches,time_step,X_size,Y_size,filters]` you'll have the last frame at slice `x[:, -1]` (TensorFlow supports NumPy style indexing).

**Comment by miaoqinghua** [comment]
Thanks~
