### ISSUE TITLE
TypeError: 'Tensor' object is not iterable.

### ISSUE THREAD

**Issue by shamitlal** [carlthome/tensorflow-convlstm-cell#27]
Hi,
While trying to execute:
**outputs, state = tf.nn.dynamic_rnn(cell, inputs, dtype=inputs.dtype)**
I am getting exception:
**TypeError: 'Tensor' object is not iterable.**
This error occurs when the following code is executed:
c, h = state

**Comment by carlthome** [comment]
What's your `cell` and `inputs` precisely?

**Comment by shamitlal** [comment]
cell = ConvLSTMCell([64,64], 64, [3,3])
input is a tensor of shape : conv2_2 = [26,10,64,64,32]
where format is : [batch_size,sequence_length,image_row,image_column,input_filters]

**Comment by carlthome** [comment]
Are you running the latest version of TensorFlow? `print(tf.VERSION)`

**Comment by carlthome** [comment]
Ping @shamitlal

**Comment by carlthome** [comment]
Is this still an issue @shamitlal?

**Comment by shamitlal** [comment]
@carlthome No, it's not an issue now.
