### ISSUE TITLE
Don't flatten and expand on each cell.__call__

### ISSUE THREAD

**Issue by carlthome** [carlthome/tensorflow-convlstm-cell#4]
http://stackoverflow.com/questions/41549784/can-tensorflow-rnncell-have-more-dimensions-than-3d

**Comment by qinenergy** [comment]
Use the following rnn wrapper:
```Python
def _rnn_wrapper(cell, inputs, timestep, batch_size):
  with tf.variable_scope("-clstm") as scope:
    state = cell.zero_state(batch_size)
    inputs = tf.unstack(inputs, axis=1)
    outputs = []
    for i in range(timestep):
        if i > 0:
          scope.reuse_variables()
        output, state = cell(inputs[i], state)
        outputs.append(output)
    outputs = tf.stack(outputs, axis=1)
  return outputs, state
```

**Comment by carlthome** [comment]
Moving the operations into another function doesn't change the fact that reshaping happens. I'd like to avoid it entirely.

**Comment by qinenergy** [comment]
Check my repo at https://github.com/qinenergy/Conv-LSTM-Cell.
I've modified the lstm cell so it accepts 4D input.
Using the new cell along with the _rnn_wrapper should enable you to avoid the reshaping stuff.

**Comment by carlthome** [comment]
Thanks for the link. It looks like you've implemented an alternative to `tf.nn.dynamic_rnn` instead. Your RNN API doesn't use `initial_state`, or handle variable sequence lengths (repeat cell state after sequence ended, up to end of minibatch), etc. You also seem to assume unrolling is wanted. Am I right?

**Comment by qinenergy** [comment]
Yeah, haven't done them yet. My point is that we have to implement our own wrapper in order to avoid reshaping.

**Comment by carlthome** [comment]
It would be preferable if TensorFlow's RNN API supported more dimensions instead. We should not have to reinvent the wheel.

**Comment by marcociccone** [comment]
agree with @carlthome... I really hate the fact that reshape is needed. Btw I don't think using vanilla for loop is efficient. `dynamic_rnn`uses scan operation if I correctly understood.

**Comment by carlthome** [comment]
Possibly fixed on TensorFlow master: https://github.com/tensorflow/tensorflow/pull/5142#issuecomment-292239105

**Comment by carlthome** [comment]
https://github.com/carlthome/tensorflow-convlstm-cell/commit/f92dbf41a79ef1cc5ca8b451b2769f54d6846f23

**Comment by marcociccone** [comment]
I didn't have time to check, but does it work with variable batch and sizes?

**Comment by carlthome** [comment]
Variable batch size should be fine. Variable height and width will not work (zero pad images before instead). I think it should be fine to have variable sequence lengths but I'm not sure.
