### ISSUE TITLE
RNNCell not found on contrib rnn package.

### ISSUE THREAD

**Issue by monkeybutter** [carlthome/tensorflow-convlstm-cell#9]
First of all thank you very much for contributing this code. I was looking for testing the ConvLSTM structure with some data and it looks that you've implemented it. I'm quite new to TensorFlow and I'm having some trouble with testing your code.

On line 3 of the cell.py file there is:
``` 
class ConvLSTMCell(tf.contrib.rnn.RNNCell):
```
Which throughs an error complaining of `to.contrib.rnn` not containing `RNNCell`. I've gone through the different versions of TensorFlow and I cannot find a reference to `RNNCell` even on the latest release. What version are you using? Am I doing something wrong?

Thank you very much for your help,
Pablo

**Comment by carlthome** [comment]
Which version of TensorFlow are you using? For [TensorFlow 1.0](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/RNNCell) the RNNCell is in `tf.contrib.rnn.RNNCell`. In earlier releases it was in core.

**Comment by carlthome** [comment]
Also, for reference, you can see that the README example is working [on the CI](https://travis-ci.org/carlthome/tensorflow-convlstm-cell/builds/216328376). Dig through the build log for information about how to install dependencies properly on a fresh Ubuntu install, if you need to.

**Comment by monkeybutter** [comment]
Thanks @carlthome, I'm using version 0.9 which as you said has `RNNCell` defined in core.

In case someone runs into the same problem this is the import that makes it work with version before 1.0:

```
from tensorflow.python.ops import rnn_cell
class ConvLSTMCell(rnn_cell.RNNCell):
...
```

**Comment by carlthome** [comment]
https://github.com/carlthome/tensorflow-convlstm-cell/commit/a647de6b86eff4c4bb502205d0ff9c1262869f19

**Comment by carlthome** [comment]
That import is not the only thing that changed between TensorFlow 0.9 and 1.0. I recommend sticking with 1.0 or newer.
